# Generated by Django 2.1.1 on 2019-05-13 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('comment', models.TextField(max_length=500)),
                ('contact', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.Contact')),
            ],
        ),
    ]
